#!/bin/bash

CACHE_DIR="${HOME}/.cache/icetone-examples"
buildno="$(cat /usr/lib/icetone-examples/buildno 2>/dev/null)"
if [ ! -f buildno -o "${buildno}" != "$(cat buildno 2>/dev/null)" ]; then
	echo "Detected launcher uprade, clearing cache"
	rm -fr "${CACHE_DIR}"
	echo "${buildno}" > buildno	
fi	
mkdir -p "${CACHE_DIR}"
pushd "${CACHE_DIR}"
for i in /usr/lib/icetone-examples/* ; do
	basename="$(basename ${i})"
	if [ ! -f "${basename}" -a ! -L "${basename}" ]; then
		ln -s "${i}" . 2>/dev/null
	fi
done
java -jar /usr/lib/icetone-examples/getdown.jar .